---

- name: Set up /etc/hosts.
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/hosts
    owner: root
    group: "{{ hosts_file_group }}"
    mode: 0644
  with_first_found:
    - files:
        - "{{ 'hosts_' + inventory_hostname + '.j2' }}"
        - hosts.j2
      paths:
        - ../templates
  when: hosts_override_hosts_template is not defined

- name: Set up /etc/hosts (override).
  ansible.builtin.template:
    src: "{{ server_override_hosts }}"
    dest: /etc/hosts
    owner: root
    group: "{{ hosts_file_group }}"
    mode: 0644
  when: hosts_override_hosts_template is defined
