---
# tasks file for hosts

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'FreeBSD'

- name: Set hostname
  ansible.builtin.include_tasks: hostname.yml
# Docker does not let you modify /etc/hosts
- name: Create /etc/hosts file from template
  ansible.builtin.include_tasks: hosts.yml
  when: ansible_virtualization_type != 'docker'
