---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: test.mydomain.net
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      test.mydomain.net:
        ansible_connection: podman
verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
