---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Verify /etc/hosts file exists and has correct permissions
      stat:
        path: /etc/hosts
      register: hosts_file_stat

    - name: Assert /etc/hosts file properties
      assert:
        that:
          - hosts_file_stat.stat.exists
          - hosts_file_stat.stat.pw_name == 'root'
          - hosts_file_stat.stat.gr_name == 'root'
          - hosts_file_stat.stat.mode == '0644'
        fail_msg: "/etc/hosts file does not have expected properties"
        success_msg: "/etc/hosts file has correct permissions and ownership"

    - name: Read /etc/hosts content
      slurp:
        src: /etc/hosts
      register: hosts_content

    - name: Assert /etc/hosts contains expected hostname
      assert:
        that:
          - "'test.mydomain.net' in (hosts_content.content | b64decode)"
        fail_msg: "/etc/hosts does not contain 'test.mydomain.net'"
        success_msg: "/etc/hosts contains expected hostname"

    - name: Verify /etc/hostname file exists and has correct permissions
      stat:
        path: /etc/hostname
      register: hostname_file_stat

    - name: Assert /etc/hostname file properties
      assert:
        that:
          - hostname_file_stat.stat.exists
          - hostname_file_stat.stat.pw_name == 'root'
          - hostname_file_stat.stat.gr_name == 'root'
          - hostname_file_stat.stat.mode == '0644'
        fail_msg: "/etc/hostname file does not have expected properties"
        success_msg: "/etc/hostname file has correct permissions and ownership"

    - name: Read /etc/hostname content
      slurp:
        src: /etc/hostname
      register: hostname_content

    - name: Assert /etc/hostname contains expected content
      assert:
        that:
          - "'test' in (hostname_content.content | b64decode)"
        fail_msg: "/etc/hostname does not contain 'test'"
        success_msg: "/etc/hostname contains expected content"
